name = "ConvexSampling"
uuid = "11d2b6ea-33ce-4b4d-a547-2ef600a65ac9"
authors = ["Maha Chaudhry"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1"
